import { GetServerSideProps } from "next";
import Head from "next/head";
import Image from "next/image";
import { fetchUsers } from "../libs/users";
import styles from "../styles/Home.module.css";

export type User = {
  id: string;
  name: string;
};

export default function Home(props: { users: User[] }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome</h1>

        <button>{'<<'}</button>
        <div>
          {(function () {  // fix me
            const list = [];
            for (let i = 0; i < props.users.length; i++) {
              list.push(
                <li>
                  {props.users[i].name}
                </li>
              );
            }
            return <ul>{list}</ul>;
          })()}
        </div>
        <button>{'>>'}</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  const users = await fetchUsers(3, 0)

  return {
    props: {
      users,
    },
  };
};
