version: "3"
services:
  app:
    ports:
      - 3000:3000
    image: interview-form
    build:
      context: .
      dockerfile: Dockerfile
    container_name: interview-form
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
