version: "3.9"
services:
  app:
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    container_name: interview-timeline
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
